# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b257f4fa1132c3045387203fb24ed5f7c736adc8d25cf86d09b79810f1967212adcff0c07b40dc29b90ab0086fd0f3d4a3fc4ea3e42a5cceee01c0fc0032fa

test:
  secret_key_base: 70a7b2081d31e2056a8729dc762a96f143596eec29fd77a891121483a4f091cffe5b4bb28a94e410b2f83a7532914bd07dc7baa61e7062ac7a5bc5d42eb6bf9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
